FROM ubuntu:22.04

WORKDIR /app/

COPY scripts/install.sh ./

RUN bash install.sh

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV TOOLCHAIN_DIR=/opt/musl
ENV CC="$TOOLCHAIN_DIR/bin/gcc"
ENV MAVEN_HOME=/opt/maven
ENV JAVA_HOME=/opt/graalvm
ENV GRAALVM_HOME=/opt/graalvm
ENV PATH="${JAVA_HOME}/bin:${MAVEN_HOME}/bin:$TOOLCHAIN_DIR/bin:${PATH}"

LABEL MAINTAINER="Har01d"

ENV TZ=Asia/Shanghai

RUN apk add --no-cache tzdata curl && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata && \
    mkdir -p /opt/atv/data /opt/atv/log

WORKDIR /opt/atv/

COPY config/alist.json /

COPY scripts/index.sh /

COPY entrypoint-standalone.sh /entrypoint.sh
COPY init.sh /
COPY scripts/h2-2.1.214.jar /

COPY data/update.sql /
COPY data/tvbox.zip /
COPY data/index.share.zip /
COPY data/cat.zip /
COPY data/pg.zip /
COPY data/zx.zip /
COPY data/data.zip /
COPY data/base_version /

COPY target/atv ./

COPY data/version /app_version

COPY --from=builder /app/atv-cli /

RUN chmod +x /entrypoint.sh

COPY target/alist-tvbox-1.0.jar app.jar

EXPOSE 4567

ENTRYPOINT ["/entrypoint.sh"]

CMD ["--spring.profiles.active=standalone"]